apps/availability/urls.py
from django.urls import path

from apps.availability.pincode.views import PincodeSelector
from apps.availability.zones.views import *

pincode_selector = PincodeSelector.as_view()
zone_list = ZoneSelector.as_view()
zone_create = ZoneCreate.as_view()
zone_update = ZoneUpdate.as_view()
zone_delete = ZoneDelete.as_view()
app_name = 'availability'


urlpatterns = [
    path('pincode/', pincode_selector, name='pincode-selector'),
    path('zones/', zone_list, name='zones-list'),
    path('zones/create/', zone_create, name='zones-create'),
    path('zones/<int:pk>/update/', zone_update, name='zones-update'),
    path('zones/<int:pk>/delete/', zone_delete, name='zones-delete'),
]

apps/logistics/urls.py
from django.urls import path, include
from rest_framework.decorators import api_view

from apps.api_set.views.orders import _login_required
from apps.logistics.views.generic import *
from apps.logistics.views import delivery_boy


app_name = 'logistics'


@api_view(['GET', 'POST'])
@_login_required
def test_push(request):
    """
    {
        "title": "Grocery App Push Notification Testing!",
        "message": "if you need some specific message",
        "action": "just_popup_action"
    }

    """
    if request.method == 'POST':
        title = request.data.get('title', 'Grocery App Push Notification Testing!')
        message = request.data.get('message', 'Some Long Message')
        from apps.utils.pushnotifications import PushNotification
        PushNotification(request.user).send_message(title, message)
        return Response({'response': 'success'})
    return Response({'response': 'try post method'})


urlpatterns = [
    path('delivery-agent/', include([
        path('', delivery_boy.DeliveryBoyList.as_view(), name=f"dashboard-delivery-boy-list"),
        path('add/', delivery_boy.DeliveryBoyCreate.as_view(), name=f"dashboard-delivery-boy-create"),
        path('promote/', delivery_boy.promote_user, name=f"dashboard-delivery-boy-promote"),
        path('<int:pk>/update/', delivery_boy.DeliveryBoyUpdate.as_view(), name=f"dashboard-delivery-boy-update-form"),
        path('<int:pk>/', delivery_boy.actions, name=f"dashboard-delivery-boy-update"),
        path('action/<int:pk>/', delivery_boy.actions, name=f"dashboard-delivery-boy-update"),
    ])),

    path('trips/', include([

        path('new/', TripCreateView.as_view(), name="new-trip"),
        path('<int:pk>/', TripUpdateView.as_view(), name="update-trip"),
        path('<int:pk>/action/', trip_update_status_view, name="update-trip-status"),

        path('planned/', PlannedTripsListView.as_view(), name="planned-trips"),
        path('active/', ActiveTripsListView.as_view(), name="active-trips"),
        path('delivered/', DeliveredTripsListView.as_view(), name="delivered-trips"),
        path('cancelled/', CancalledTripsListView.as_view(), name="cancelled-trips"),

    ])),
    path('scheduled-time-slots/', ScheduledTimeSlotList.as_view(), name="scheduledtimeslot-list"),
    path('test-push/', test_push, name="test_push"),
    path('slot/', include([
        # path('', SlotListView.as_view(), name="slot-list"),
    ])),
]

couriers/delhivery/urls.py
from django.urls import path, include
from couriers.delhivery.views import *

app_name = 'dashboard-pickup'

urlpatterns = [
    path('pickup/', include([
        path('', DashboardPickupListView.as_view(), name='list'),
        path('create/', DashboardPickupCreateView.as_view(), name='create'),
        path('<int:pk>/update>/', DashboardPickupUpdateView.as_view(), name='update'),
        path('<int:pk>/delete/', DashboardPickupDeleteView.as_view(), name='delete'),
    ]))
]

osc/urls.py
import os

import debug_toolbar
from django.apps import apps
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.models import FlatPage
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from django.contrib.sitemaps.views import sitemap
from django.shortcuts import render
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.generic import TemplateView
from rest_framework.decorators import api_view
from rest_framework.documentation import include_docs_urls
from rest_framework.generics import get_object_or_404
from rest_framework.response import Response

from apps.dashboard.catalogue.views import ProductRedirectView, CatalogueRedirectView
from apps.mod_oscarapi.views.checkout import CheckoutView
from django.views.i18n import JavaScriptCatalog

view_checkout = never_cache(CheckoutView.as_view())


@api_view()
def policy_html(request, path):
    flatpage = get_object_or_404(FlatPage.objects.filter(), url=path)
    return Response({
        'title': flatpage.title,
        'url': flatpage.url,
        'content': flatpage.content,
        'registration_required': flatpage.registration_required,
    })


urlpatterns = [
    path('api/v1/checkout/', view_checkout, name='api-checkout'),                   # Must be before oscar_api.urls
    path('api/v2/checkout/', view_checkout, name='api-checkout'),                   # Must be before oscar_api.urls
    # path('api/v1/', include(apps.get_app_config("oscarapicheckout").urls[0])),    # Must be before oscar_api.urls

    path('api/v1/', include('oscarapi.urls')),
    path('api/v1/buy-now/', include('apps.buynow.urls')),
    path('api/v2/', include('oscarapi.urls')),
    path('api/v2/buy-now/', include('apps.buynow.urls')),

    path('api/', include('apps.api_set.urls')),                                      # prone to versioning
    path('api/v2/', include('apps.api_set_v2.urls')),                                # prone to versioning

    path('api/v1/', include('apps.logistics.apis')),                                 # prone to versioning
    path('api/v2/', include('apps.logistics.apis')),                                 # prone to versioning

    path('api/v2/avalilability/', include('apps.availability.api')),
    path('api/v1/avalilability/', include('apps.availability.api')),
    path('dashboard/avalilability/', include('apps.availability.urls')),
    path('dashboard/logistics/', include('apps.logistics.urls')),
    path('dashboard/orders/', include('apps.order.timeslot.urls')),
    path('dashboard/ranges/', include('apps.dashboard.ranges.urls')),
    # path('dashboard/communication/', include('apps.dashboard.communications.urls')),
    # https://github.com/django-oscar/django-oscar-accounts
    path('dashboard/accounts/', apps.get_app_config('accounts_dashboard').urls),

    # path('catalogue/<slug:slug>'+'_<int:pk>/', ProductRedirectView.as_view(), name='product-detail-api'),###API of product detail
    # path('catalogue/', CatalogueRedirectView.as_view(), name='catalogue_redirect'),

    # path(r'dashboard/payments/cod/', include(cod_app.urls)),
    path('sitemap.xml', sitemap,
         {'sitemaps': {'flatpages': FlatPageSitemap}},
         name='django.contrib.sitemaps.views.sitemap'),

    path('api/docs/', include_docs_urls(title='Fegno Store API', public=True)),
    path('i18n/', include('django.conf.urls.i18n')),  # > Django-2.0
    path('admin/', admin.site.urls),

    path('api/v2/push/', include('apps.utils.push_urls')),
    path('api/v1/push/', include('apps.utils.push_urls')),
    path('api/v2/policies<path:path>', policy_html, name="policies"),
    path('dashboard/', include('couriers.delhivery.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.dashboard.custom.urls')),
    path('', include(apps.get_app_config('oscar').urls[0])),  # > Django-2.0

    # url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

# if 'stores' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         # basic configuration for Oscar
#         path('', include(apps.get_app_config('oscar').urls[0])),
#         # adds URLs for the dashboard store manager
#         path('dashboard/stores/', apps.get_app_config('stores_dashboard').urls),
#         # adds URLs for overview and detail pages
#         path('stores/', apps.get_app_config('stores').urls),
#         # adds internationalization URLs
#         path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
#     ]


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls))),
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, "assets"))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path('qs/', TemplateView.as_view(template_name="dummy_search.html")),  # > Django-2.0
    urlpatterns += path('sentry-debug/', lambda request: 1 / 0),


def error_404(request, exception=None):
    return render(request, '404.html', status=404)


def error_500(request, exception=None):
    return render(request, '500.html', status=500)


def error_400(request, exception=None):
    return render(request, '400.html', status=400)


def error_403(request, exception=None):
    return render(request, '403.html', status=403)


handler500 = error_500
handler403 = error_403
handler400 = error_400
handler404 = error_404

couriers/delhivery/models.py
import json

from django.conf import settings
from django.db import models
from django.utils.functional import cached_property
from jsonfield import JSONField
from oscar.apps.order import exceptions

from apps.order.models import Order
from couriers.delhivery.facade import Delhivery


class RequestPickUp(models.Model):
    response = JSONField(default=None, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    date = models.DateField(null=True)
    time = models.TimeField(null=True)
    completed = models.BooleanField(null=True)

    @property
    def response_html(self) -> str:
        if self.response is None:
            return "-"
        html = "<ol>{}</ol>"
        inner_html = ""
        for key, val in self.response.items():
            key = " ".join([(k[0].upper() + k[1:]) for k in key.split('_')])
            inner_html += "<li>{}: <b>{}</b></li>".format(key, val)
        return html.format(inner_html)


class DelhiveryResponse(models.Model):
    pincode = models.CharField(max_length=6, primary_key=True, unique=True)
    response = JSONField(null=True, blank=True)
    status = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    @classmethod
    def verify(cls, pincode):
        if not pincode.isdigit() or not len(pincode) == 6:
            return False, {
                "status": "pincode_invalid",
                "status_text": "Invalid Pincode"
            }

        if pincode[:2] not in ['67', '68', '69']:
            return False, {
                "status": "no_delivery_available_outside_kerala",
                "status_text": "Currently we are delivering only inside Kerala! Soon we might Reach There!"
            }
        existing_pincode = cls.objects.filter(pincode=pincode).first()
        if existing_pincode:
            return existing_pincode.status, existing_pincode.response
        from couriers.delhivery.facade import Delhivery
        delhivery = Delhivery()
        response = delhivery.pincode_servicibility(pincode)
        instance = cls.objects.create(
            response=(response or {
                'status_text': 'We could not Deliver to this Location',
                'status': 'could_not_deliver_to_location',
            }),
            pincode=pincode,
            status=(response and response['pre_paid'] == 'Y') or False
        )
        return instance.status, instance.response

couriers/delhivery/views.py
import datetime
from django import forms
from django.conf import settings
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django.utils import timezone

from apps.order.models import Order
from couriers.delhivery.facade import Delhivery
from couriers.delhivery.models import RequestPickUp


class DashboardPickupListView(ListView):
    model = RequestPickUp
    ordering = ('-id', )


class DashboardPickupUpdateView(UpdateView):
    model = RequestPickUp
    fields = ('completed', )
    success_url = reverse_lazy('dashboard-pickup:list')

    def form_valid(self, form):
        form.instance.completed = True
        self.object = form.save()
        from couriers.delhivery.signals import delivery_picked_up
        print("POINT - 01")
        delivery_picked_up.send(instance=form.instance, sender=self)
        print("POINT - END")
        return HttpResponseRedirect(self.success_url)


class PickupRequestForm(forms.ModelForm):
    expected_orders = forms.IntegerField()

    def __init__(self, *args, **kwargs):
        super(PickupRequestForm, self).__init__(*args, **kwargs)
        to_pick_statuses = (settings.ORDER_STATUS_PACKED, settings.ORDER_STATUS_CONFIRMED)
        self.fields['expected_orders'].initial = Order.objects.filter(status__in=to_pick_statuses).count()

    class Meta:
        model = RequestPickUp
        fields = ('date', 'time', 'expected_orders')

    def clean_date(self):
        date = self.cleaned_data['date']
        if date < timezone.now().date():
            raise forms.ValidationError("Date needs to be a futurestic date")
        return date

    def clean_time(self):
        date = self.cleaned_data['date']
        time = self.cleaned_data['time']
        if date == timezone.now().date() and time <= timezone.now().time():
            raise forms.ValidationError("Time needs to be a futurestic time")
        if not (datetime.time(hour=9) <= time <= datetime.time(hour=21)):
            raise forms.ValidationError("Shipment can be delivered only between 09:00 AM and 09:00 PM ")
        return time


class DashboardPickupCreateView(CreateView):
    model = RequestPickUp
    form_class = PickupRequestForm
    success_url = reverse_lazy('dashboard-pickup:list')

    def form_valid(self, form):
        instance = form.instance
        d = Delhivery()
        response = d.request_pickup(instance.date, instance.time, instance)
        if response is not None and not response.get('pr_exist'):
            instance.save()
            return HttpResponseRedirect(self.success_url)
        default_message = "Invalid response form Delivery partner! please try again!"
        messages.error(self.request, (response or {}).get('error', {}).get('message', default_message))
        return self.form_invalid(form)


class DashboardPickupDeleteView(DeleteView):
    model = RequestPickUp

templates/delhivery/requestpickup_form.html
{% extends 'oscar/dashboard/layout.html' %}
{% load i18n humanize %}

{% block title %}
Pickups | {{ block.super }}
{% endblock %}
{% block body_class %} {{ block.super }} Pickups {% endblock %}
{% block navbar %}
{% if not is_popup %}
{{ block.super }}
{% endif %}
{% endblock %}
{% block dashboard_nav %}
{% if not is_popup %}
{{ block.super }}
{% endif %}
{% endblock %}
{% block breadcrumbs %}

<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
    </li>
    <li >
        <a href="{% url 'dashboard-pickup:list' %}">Pickups</a>
    </li>
    <li class="active">
        Pickups
    </li>
</ul>
{% endblock %}

{% block header %}
<div class="page-header">
    <h1> Request new Pickup!</h1>
</div>
{% endblock header %}

{% block dashboard_content %}
<div class="table-header">
    <h2>Pickups</h2>
</div>
<style>
.animatemove{
  animation: MoveUpDown 1s linear infinite;
  position: relative;
}
@keyframes MoveUpDown {
  0%, 100% {top: 0px;}
  50% {top: 5px}
}
</style>
<div class="well">
    {% if another_pickup_permitted %}
    <table class="table table-stripped ">
        <caption> Sorry! Your last request is not yet Collected, Any order until then will be picked up on arrival! </caption>
    </table>

    {% else %}
    <div class="row">
        <div class="col-md-2 row-eq-height"  style="text-align:center; padding-top:60px;">
            <img src="https://shopichigo.com/wp-content/uploads/2016/12/box-icon.png" height="140px">
        </div>
        <div class="col-md-6 row-eq-height">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="btn btn-info"> Request a Pickup! </button>
            </form>

        </div>
        <div class="col-md-4 row-eq-height"  style="text-align:center; padding-top:60px;">
            <img src="https://cl.delhivery.com/assets/images/thank-you-truck.png" class="animatemove" height="140px">
        </div>
    </div>
    {% endif %}
</div>
<script>
    var date_input = document.getElementById('id_date');
    var time_input = document.getElementById('id_time');
    var expected_orders = document.getElementById('id_expected_orders');
    if (expected_orders) expected_orders.classList.add('form-control');

    if (date_input && time_input){
        date_input.setAttribute('type', 'date');
        date_input.classList.add('form-control');
        time_input.setAttribute('type', 'time');
        time_input.classList.add('form-control');
        time_input.classList.add('form-control');

        var date = new Date();
        date.setDate(date.getDate() + 1);

        var day = date.getDate();
        var month = date.getMonth() + 1;
        var year = date.getFullYear();

        if (month < 10) { month = "0" + month };
        if (day < 10) { day = "0" + day };

        var tomorrow = year + "-" + month + "-" + day;
        console.log(tomorrow);
        date_input.setAttribute('value',  tomorrow);
        time_input.value = '10:00' ;
    }

</script>
{% endblock dashboard_content %}

templates/delhivery/requestpickup_list.html
{% extends 'oscar/dashboard/layout.html' %}
{% load i18n humanize %}

{% block title %}
Pickups | {{ block.super }}
{% endblock %}
{% block body_class %} {{ block.super }} Pickups {% endblock %}
{% block navbar %}
{% if not is_popup %}
{{ block.super }}
{% endif %}
{% endblock %}
{% block dashboard_nav %}
{% if not is_popup %}
{{ block.super }}
{% endif %}
{% endblock %}
{% block breadcrumbs %}
<ul class="breadcrumb">
    <li>
        <a href="{% url 'dashboard:index' %}">{% trans "Dashboard" %}</a>
    </li>
    <li class="active">
        Pickups
    </li>
</ul>
{% endblock %}

{% block header %}
<div class="page-header">
    <h1><a href="{% url 'dashboard-pickup:create' %}" class="btn btn-primary btn-lg pull-right">
        <i class="icon-plus"></i> Request New Pickup</a>
        Pickups </h1>
</div>
{% endblock header %}

{% block dashboard_content %}
<div class="table-header">
    <h2>Pickups</h2>
</div>
<div class="well">
    <table class="table table-stripped ">
        <thead>
        <tr>
            <th class="table-header">ID</th>
            <th class="table-header">Pickup Requested Date</th>
            <th class="table-header">Pickup Expected Date</th>
            <th class="table-header">Response</th>
            <th class="table-header">Status</th>
            <th class="table-header">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.created_at|naturaltime }}</td>
            <td>{{ object.date }}, {{ object.time }} </td>
            <td>{{ object.response_html|safe }}</td>
            <td>
                {% if not object.completed %}
                    <img src="{{ STATIC_URL }}img/processing.gif" height="30px">
                {% else %}
                    <img src="{{ STATIC_URL }}img/tick.jpeg" height="30px">
                {% endif %}
            </td>
            <td>{% if not object.completed %}
                <form action="{% url 'dashboard-pickup:update' pk=object.pk %}" method="post">
                    <input type="hidden" hidden  name="completed" value="1">
                    <button class="btn btn-success" type="submit">Mark as Collected!</button>
                    <small class="text-muted"> This will update status of  all 'PACKED' orders to 'SHIPPED'</small>
                </form>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

</div>
{% endblock dashboard_content %}